---

- hosts: blackmesh
  remote_user: 401e
  gather_facts: no
  roles:
    - apache
    - mysql
    - application
  vars:
    # Project
    site_name: # Typically, the name of the github repo
    drupal_root: site # Dir which has index.php
    git_branch: develop # This is the branch that will be deployed
    max_releases: 10 # Number of past releases to keep

    # Host mysql
    db_name: # name of the db
    db_user: # name of the db user
    db_pass: # db password

    # Host apache
    site_domain: # domain name to put in vhost. Should NOT have www.

    # Host filesystem
    htdocs: htdocs # document root expected by apache
    htsdocs: htsdocs # ibid.
    file_owner: 401e
    file_group: 401e
    sites_directory: /var/www
